export const diseaseOptions = [
  { value: "itching", label: "Itching", isFixed: false },
  { value: "skin_rash", label: "Skin Rash", isFixed: false },
  {
    value: "nodal_skin_eruptions",
    label: "Nodal Skin Eruptions",
    isFixed: false,
  },
  {
    value: "continuous_sneezing",
    label: "Continuous Sneezing",
    isFixed: false,
  },
  { value: "shivering", label: "Shivering", isFixed: false },
  { value: "chills", label: "Chills", isFixed: false },
  { value: "joint_pain", label: "Joint Pain", isFixed: false },
  { value: "stomach_pain", label: "Stomach Pain", isFixed: false },
  { value: "acidity", label: "Acidity", isFixed: false },
  { value: "ulcers_on_tongue", label: "Ulcers on Tongue", isFixed: false },
  { value: "muscle_wasting", label: "Muscle Wasting", isFixed: false },
  { value: "spotting_urination", label: "Spotting Urination", isFixed: false },
  { value: "fatigue", label: "Fatigue", isFixed: false },
  { value: "weight_gain", label: "Weight Gain", isFixed: false },
  { value: "anxiety", label: "Anxiety", isFixed: false },
  {
    value: "cold_hands_and_feets",
    label: "Cold Hands and Feet",
    isFixed: false,
  },
  { value: "mood_swings", label: "Mood Swings", isFixed: false },
  { value: "weight_loss", label: "Weight Loss", isFixed: false },
  { value: "restlessness", label: "Restlessness", isFixed: false },
  { value: "lethargy", label: "Lethargy", isFixed: false },
  { value: "patches_in_throat", label: "Patches in Throat", isFixed: false },
  {
    value: "irregular_sugar_level",
    label: "Irregular Sugar Level",
    isFixed: false,
  },
  { value: "cough", label: "Cough", isFixed: false },
  { value: "high_fever", label: "High Fever", isFixed: false },
  { value: "sunken_eyes", label: "Sunken Eyes", isFixed: false },
  { value: "breathlessness", label: "Breathlessness", isFixed: false },
  { value: "sweating", label: "Sweating", isFixed: false },
  { value: "dehydration", label: "Dehydration", isFixed: false },
  { value: "indigestion", label: "Indigestion", isFixed: false },
  { value: "headache", label: "Headache", isFixed: false },
  { value: "yellowish_skin", label: "Yellowish Skin", isFixed: false },
  { value: "dark_urine", label: "Dark Urine", isFixed: false },
  { value: "nausea", label: "Nausea", isFixed: false },
  { value: "loss_of_appetite", label: "Loss of Appetite", isFixed: false },
  {
    value: "pain_behind_the_eyes",
    label: "Pain Behind the Eyes",
    isFixed: false,
  },
  { value: "back_pain", label: "Back Pain", isFixed: false },
  { value: "constipation", label: "Constipation", isFixed: false },
  { value: "abdominal_pain", label: "Abdominal Pain", isFixed: false },
  { value: "diarrhoea", label: "Diarrhoea", isFixed: false },
  { value: "mild_fever", label: "Mild Fever", isFixed: false },
  { value: "yellow_urine", label: "Yellow Urine", isFixed: false },
  { value: "yellowing_of_eyes", label: "Yellowing of Eyes", isFixed: false },
  {
    value: "acute_liver_failure",
    label: "Acute Liver Failure",
    isFixed: false,
  },
  { value: "fluid_overload", label: "Fluid Overload", isFixed: false },
  {
    value: "swelling_of_stomach",
    label: "Swelling of Stomach",
    isFixed: false,
  },
  {
    value: "swelled_lymph_nodes",
    label: "Swelled Lymph Nodes",
    isFixed: false,
  },
  { value: "malaise", label: "Malaise", isFixed: false },
  {
    value: "blurred_and_distorted_vision",
    label: "Blurred and Distorted Vision",
    isFixed: false,
  },
  { value: "phlegm", label: "Phlegm", isFixed: false },
  { value: "throat_irritation", label: "Throat Irritation", isFixed: false },
  { value: "redness_of_eyes", label: "Redness of Eyes", isFixed: false },
  { value: "sinus_pressure", label: "Sinus Pressure", isFixed: false },
  { value: "runny_nose", label: "Runny Nose", isFixed: false },
  { value: "congestion", label: "Congestion", isFixed: false },
  { value: "chest_pain", label: "Chest Pain", isFixed: false },
  { value: "weakness_in_limbs", label: "Weakness in Limbs", isFixed: false },
  { value: "fast_heart_rate", label: "Fast Heart Rate", isFixed: false },
  {
    value: "pain_during_bowel_movements",
    label: "Pain During Bowel Movements",
    isFixed: false,
  },
  {
    value: "pain_in_anal_region",
    label: "Pain in Anal Region",
    isFixed: false,
  },
  { value: "bloody_stool", label: "Bloody Stool", isFixed: false },
  { value: "irritation_in_anus", label: "Irritation in Anus", isFixed: false },
  { value: "neck_pain", label: "Neck Pain", isFixed: false },
  { value: "dizziness", label: "Dizziness", isFixed: false },
  { value: "cramps", label: "Cramps", isFixed: false },
  { value: "bruising", label: "Bruising", isFixed: false },
  { value: "obesity", label: "Obesity", isFixed: false },
  { value: "swollen_legs", label: "Swollen Legs", isFixed: false },
  {
    value: "swollen_blood_vessels",
    label: "Swollen Blood Vessels",
    isFixed: false,
  },
  {
    value: "puffy_face_and_eyes",
    label: "Puffy Face and Eyes",
    isFixed: false,
  },
  { value: "enlarged_thyroid", label: "Enlarged Thyroid", isFixed: false },
  { value: "brittle_nails", label: "Brittle Nails", isFixed: false },
  {
    value: "swollen_extremities",
    label: "Swollen Extremities",
    isFixed: false,
  },
  { value: "excessive_hunger", label: "Excessive Hunger", isFixed: false },
  {
    value: "extra_marital_contacts",
    label: "Extra Marital Contacts",
    isFixed: false,
  },
  {
    value: "drying_and_tingling_lips",
    label: "Drying and Tingling Lips",
    isFixed: false,
  },
  { value: "slurred_speech", label: "Slurred Speech", isFixed: false },
  { value: "knee_pain", label: "Knee Pain", isFixed: false },
  { value: "hip_joint_pain", label: "Hip Joint Pain", isFixed: false },
  { value: "muscle_weakness", label: "Muscle Weakness", isFixed: false },
  { value: "stiff_neck", label: "Stiff Neck", isFixed: false },
  { value: "swelling_joints", label: "Swelling Joints", isFixed: false },
  { value: "movement_stiffness", label: "Movement Stiffness", isFixed: false },
  { value: "spinning_movements", label: "Spinning Movements", isFixed: false },
  { value: "loss_of_balance", label: "Loss of Balance", isFixed: false },
  { value: "unsteadiness", label: "Unsteadiness", isFixed: false },
  {
    value: "weakness_of_one_body_side",
    label: "Weakness of One Body Side",
    isFixed: false,
  },
  { value: "loss_of_smell", label: "Loss of Smell", isFixed: false },
  { value: "bladder_discomfort", label: "Bladder Discomfort", isFixed: false },
  {
    value: "foul_smell_of_urine",
    label: "Foul Smell of Urine",
    isFixed: false,
  },
  {
    value: "continuous_feel_of_urine",
    label: "Continuous Feel of Urine",
    isFixed: false,
  },
  { value: "passage_of_gases", label: "Passage of Gases", isFixed: false },
  { value: "internal_itching", label: "Internal Itching", isFixed: false },
  {
    value: "toxic_look_(typhos)",
    label: "Toxic Look (Typhos)",
    isFixed: false,
  },
  { value: "depression", label: "Depression", isFixed: false },
  { value: "irritability", label: "Irritability", isFixed: false },
  { value: "muscle_pain", label: "Muscle Pain", isFixed: false },
  { value: "altered_sensorium", label: "Altered Sensorium", isFixed: false },
  {
    value: "red_spots_over_body",
    label: "Red Spots Over Body",
    isFixed: false,
  },
  { value: "belly_pain", label: "Belly Pain", isFixed: false },
  {
    value: "abnormal_menstruation",
    label: "Abnormal Menstruation",
    isFixed: false,
  },
  { value: "dischromic_patches", label: "Dischromic Patches", isFixed: false },
  { value: "watering_from_eyes", label: "Watering from Eyes", isFixed: false },
  { value: "increased_appetite", label: "Increased Appetite", isFixed: false },
  { value: "polyuria", label: "Polyuria", isFixed: false },
  { value: "family_history", label: "Family History", isFixed: false },
  { value: "mucoid_sputum", label: "Mucoid Sputum", isFixed: false },
  { value: "rusty_sputum", label: "Rusty Sputum", isFixed: false },
  {
    value: "lack_of_concentration",
    label: "Lack of Concentration",
    isFixed: false,
  },
  {
    value: "visual_disturbances",
    label: "Visual Disturbances",
    isFixed: false,
  },
  {
    value: "receiving_blood_transfusion",
    label: "Receiving Blood Transfusion",
    isFixed: false,
  },
  {
    value: "receiving_unsterile_injections",
    label: "Receiving Unsterile Injections",
    isFixed: false,
  },
  { value: "coma", label: "Coma", isFixed: false },
  { value: "stomach_bleeding", label: "Stomach Bleeding", isFixed: false },
  {
    value: "distention_of_abdomen",
    label: "Distention of Abdomen",
    isFixed: false,
  },
  {
    value: "history_of_alcohol_consumption",
    label: "History of Alcohol Consumption",
    isFixed: false,
  },
  { value: "fluid_overload", label: "Fluid Overload", isFixed: false },
  { value: "blood_in_sputum", label: "Blood in Sputum", isFixed: false },
  {
    value: "prominent_veins_on_calf",
    label: "Prominent Veins on Calf",
    isFixed: false,
  },
  { value: "palpitations", label: "Palpitations", isFixed: false },
  { value: "painful_walking", label: "Painful Walking", isFixed: false },
  { value: "pus_filled_pimples", label: "Pus-filled Pimples", isFixed: false },
  { value: "blackheads", label: "Blackheads", isFixed: false },
  { value: "scurring", label: "Scurring", isFixed: false },
  { value: "skin_peeling", label: "Skin Peeling", isFixed: false },
  {
    value: "silver_like_dusting",
    label: "Silver-like Dusting",
    isFixed: false,
  },
  {
    value: "small_dents_in_nails",
    label: "Small Dents in Nails",
    isFixed: false,
  },
  { value: "inflammatory_nails", label: "Inflammatory Nails", isFixed: false },
  { value: "blister", label: "Blister", isFixed: false },
  {
    value: "red_sore_around_nose",
    label: "Red Sore Around Nose",
    isFixed: false,
  },
  { value: "yellow_crust_ooze", label: "Yellow Crust Ooze", isFixed: false },
];
